replicaCount: 1

image:
  repository: cloudflare/cloudflared
  tag: latest
  pullPolicy: IfNotPresent

tunnel:
  name: stock-finder
  credentialsJson: |
    {
      "AccountTag": "62042f9fcd5411eb85dc581b38dce3f2",
      "TunnelID": "af6692e5-6d5a-4af3-a405-3297c2407996",
      "TunnelName": "stock-finder",
      "TunnelSecret": "RfYvnvuudIVnGht06GJ95KNNRf03lJ5Gkkkw7sxPl2w="
    }

ingress:
  - hostname: stock-finder.shop
    service: http://platform-gateway-nginx.gateway-ns.svc.cluster.local
  - hostname: app.stock-finder.shop
    service: http://platform-gateway-nginx.gateway-ns.svc.cluster.local
  - hostname: api.stock-finder.shop
    service: http://platform-gateway-nginx.gateway-ns.svc.cluster.local
  - hostname: s3.stock-finder.shop
    service: http://platform-gateway-nginx.gateway-ns.svc.cluster.local

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
